modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issueTracker}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${displayName}"
displayURL = "${displayUrl}"
logoFile = "${modId}_logo.png"
authors = "${authors}"
description = "${description}"
enumExtensions = "META-INF/enum_extensions.json"

[[mixins]]
config = "${modId}.mixins.json"

[[mixins]]
config = "${modId}-platform.neoforge.mixins.json"

[[mixins]]
config = "${modId}-compat.skinlayers3d.mixins.json"

[[mixins]]
config = "${modId}-compat.geckolib.mixins.json"

[[mixins]]
config = "${modId}-compat.vampirism.mixins.json"

[[mixins]]
config = "${modId}-compat.werewolves.mixins.json"

[[mixins]]
config = "${modId}-compat.fgm.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies."${modId}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "BOTH"
