[versions]
mod = "21.17.3"
java = "21"

# Minecraft
minecraft = "1.21.1"
parchmentMappings = "2024.11.17"

# NeoForge
neoforge = "21.1.219"
neoforgeRange = "[21,)"
moddevgradle = "2.0.134"
# https://projects.neoforged.net/neoforged/neoform
neoform = "1.21.1-20240808.144430"

# SpongePowered Mixin
mixin = "0.8.7"

# Third-party mods
forgeconfigapiport = "21.1.6"
jei = "19.21.2.313"
kubejs = "2101.7.1-build.181"
rhino = "2006.2.4-build.17"
architectury = "13.0.8"
controlify = "2.5.0+1.21.1-neoforge"
azurelib = "3.1.8"
azurelib-armor = "3.1.4"
geckolib = "4.8.3"
sodium = "mc1.21.1-0.6.13-neoforge"
iris = "1.8.12+1.21.1-neoforge"
werewolves = "1.21-2.0.2.5"
vampirism = "1.21-1.10.7"
curios = "9.5.1+1.21.1"
playerAnimator = "2.0.4+1.21.1"
skinlayers = "nVJQQoQ0" # 1.10.1
firstPersonModel = "L1VcMGVt" # 2.6.1
shoulderSurfing = "1.21.1-4.18.1+neoforge"
creativecore = "2.13.35"
playerrevive = "2.1.0"
fgm = "3.2.2"
simplytooltips = "0.1.3"
fzzy = "0.7.6+1.21+neoforge"
kotlin = "5.11.0"
simplyswords = "1.63.0-1.21.1"



# Helper Gradle-plugins
mcSafeResources = "0.0.2"
modPublish = "1.1.0"

[libraries]
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }

forgeconfigapiport-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapiport" }

jei-common-api = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }

azurelib = { module = "mod.azure.azurelib:azurelib-neo-1.21.1", version.ref = "azurelib" }
azurelib-armor = { module = "mod.azure.azurelibarmor:azurelibarmor-common-1.21.1", version.ref = "azurelib-armor" }
geckolib = { module = "software.bernie.geckolib:geckolib-neoforge-1.21.1", version.ref = "geckolib" }

sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
werewolves = { module = "maven.modrinth:werewolves", version.ref = "werewolves" }
vampirism = { module = "maven.modrinth:vampirism", version.ref = "vampirism" }

simplytooltips = {group = "maven.modrinth", name = "simply-tooltips", version.ref = "simplytooltips"}
kotlin = {group = "maven.modrinth", name = "kotlin-for-forge", version.ref = "kotlin"}
fzzy = {group = "maven.modrinth", name = "fzzy-config", version.ref = "fzzy"}


curios = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
playerAnimator = { module = "dev.kosmx.player-anim:player-animation-lib-forge", version.ref = "playerAnimator" }

kubejs = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
rhino = { module = "dev.latvian.mods:rhino-neoforge", version.ref = "rhino" }
architectury = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }

skinlayers = { module = "maven.modrinth:3dskinlayers", version.ref = "skinlayers" }
firstPersonModel = { module = "maven.modrinth:first-person-model", version.ref = "firstPersonModel" }
shoulderSurfing = { module = "maven.modrinth:shoulder-surfing-reloaded", version.ref = "shoulderSurfing" }

controlify = { module = "dev.isxander:controlify", version.ref = "controlify" }

creativeCore = { module = "maven.modrinth:creativecore", version.ref = "creativecore" }
playerRevive = { module = "maven.modrinth:playerrevive", version.ref = "playerrevive" }

fgm = {module = "maven.modrinth:female-gender", version.ref = "fgm"}
simplyswords = { group = "maven.modrinth", name = "simply-swords", version.ref = "simplyswords"}


# Declared only in libraries[], not plugins[], as it's used only by Gradle convention plugins.
modPublish-gradle-plugin = { module = "me.modmuss50.mod-publish-plugin:me.modmuss50.mod-publish-plugin.gradle.plugin", version.ref = "modPublish" }

[plugins]
# Mod-loader plugins
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }

# Helper plugins
mcSafeResources = { id = "dev.echoellet.mc-safe-resources", version.ref = "mcSafeResources" }

[bundles]

simply = ["simplytooltips", "fzzy", "kotlin", "simplyswords"]

