name: Mirror docs to EpicFight-Docs

on:
  push:
    paths:
      - "docs/**"

jobs:
  mirror:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.DOCS_MIRROR_TOKEN }}@github.com/Epic-Fight/EpicFight-Docs.git target

      - name: Sync Documents
        run: |
          if [ -d "docs/universal_docs" ]; then
            rsync -av --delete \
              --exclude='${{ github.ref_name }}/' \
              --exclude='.gitkeep' \
              docs/universal_docs/ target/docs/API/
          fi

          if [ -d "docs/version_specific" ]; then
            mkdir -p target/docs/API/${{ github.ref_name }}
            rsync -av --delete \
              --exclude='.gitkeep' \
              docs/version_specific/ target/docs/API/${{ github.ref_name }}/
          else
            echo "version_specific deleted from source. Cleaning target version folder..."
            find target/docs/API/${{ github.ref_name }} -mindepth 1 ! -name '.gitkeep' -delete
          fi

      - name: Commit and push changes
        run: |
          cd target

          AUTHOR_NAME="${{ github.event.head_commit.author.name }}"
          AUTHOR_EMAIL="${{ github.event.head_commit.author.email }}"

          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          
          git add docs/API

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync docs: ${{ github.event.head_commit.message }} (Ref: ${{ github.sha }})"
            git pull --rebase origin main
            git push
          fi
